### ISSUE TITLE
如何优雅的集成进新的gpt4all

### ISSUE THREAD

**Issue by aiandking** [vra/talkGPT4All#2]
已经星标，很棒的项目。Yunfeng Wang 👍

现在gpt4all 已经可以一键下载安装，普惠了普通人，talkgtp4all建议考虑这一点，如何高效的结合并运用起来

**Comment by vra** [comment]
感谢认可和消息的同步，我先看看GPT4All的更新，后面也同步一下talkGPT4All项目，有进展在这里同步

**Comment by vra** [comment]
hi @aiandking ，talkGPT4All已经集成了最新版的GPT4All Python 包，详情可以参考[这篇文章](https://zhuanlan.zhihu.com/p/632592897)，也可以直接查看仓库代码的更新。

**Comment by aiandking** [comment]
> 这篇文章

cool
