### ISSUE TITLE
Talk Not work

### ISSUE THREAD

**Issue by Jacksninor** [vra/talkGPT4All#8]
It seems not work on Windows 11  now.  I don't know if the root cause is blocked by TTPSConnectionPool(host='raw.githubusercontent.com'. 
It is not a serous problem. I just try to use it for fun. It might help to practice oral English learning.

(base) PS C:\Users\Administrator> talkgpt4all -m D:\Models\mpt-7b-chat-merges-q4_0.gguf
usage: talkgpt4all [-h] [--gpt-model-name GPT_MODEL_NAME] [--whisper-model-type WHISPER_MODEL_TYPE]
                   [--voice-rate VOICE_RATE]
talkgpt4all: error: unrecognized arguments: -m D:\Models\mpt-7b-chat-merges-q4_0.gguf
(base) PS C:\Users\Administrator> talkgpt4all --gpt-model-name  D:\Models\mpt-7b-chat-merges-q4_0.gguf
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

.....

  raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /nomic-ai/gpt4all/main/gpt4all-chat/metadata/models3.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019D45E1C2F0>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

**Comment by vra** [comment]
@Jacksninor , Hi, This is the network issue. The connection to GitHub is blocked. You can try again

**Comment by Jacksninor** [comment]
Thank you very much and took your time. I retried and raise new problem. It looks like Model files were not recongnised. I installed GPT4ALL v3.4.2 on windows. The application 'find models' show 'index error: http://gpt4all.io/models/models3.json'. So I found a few models from internet. It works on v3.4.2 but not for talkgpt4all. 
(base) PS C:\Users\Administrator> talkgpt4all --gtp-model-name D:\Models\gpt4all-lora-quantized.bin
usage: talkgpt4all [-h] [--gpt-model-name GPT_MODEL_NAME] [--whisper-model-type WHISPER_MODEL_TYPE] [--voice-rate VOICE_RATE]
talkgpt4all: error: unrecognized arguments: --gtp-model-name D:\Models\gpt4all-lora-quantized.bin
(base) PS C:\Users\Administrator> talkgpt4all --gtp-model-name D:\Models\mistral-7b-openorca.Q4_0.gguf
usage: talkgpt4all [-h] [--gpt-model-name GPT_MODEL_NAME] [--whisper-model-type WHISPER_MODEL_TYPE] [--voice-rate VOICE_RATE]
talkgpt4all: error: unrecognized arguments: --gtp-model-name D:\Models\mistral-7b-openorca.Q4_0.gguf
(base) PS C:\Users\Administrator>

**Comment by Jacksninor** [comment]
Thank you very much and took your time. I retried and raise new problem. It looks like Model files were not recongnised. I installed GPT4ALL v3.4.2 on windows. The application 'find models' show 'index error: http://gpt4all.io/models/models3.json'. So I found a few models from internet. It works on v3.4.2 but not for talkgpt4all. 
(base) PS C:\Users\Administrator> talkgpt4all --gtp-model-name D:\Models\gpt4all-lora-quantized.bin
usage: talkgpt4all [-h] [--gpt-model-name GPT_MODEL_NAME] [--whisper-model-type WHISPER_MODEL_TYPE] [--voice-rate VOICE_RATE]
talkgpt4all: error: unrecognized arguments: --gtp-model-name D:\Models\gpt4all-lora-quantized.bin
(base) PS C:\Users\Administrator> talkgpt4all --gtp-model-name D:\Models\mistral-7b-openorca.Q4_0.gguf
usage: talkgpt4all [-h] [--gpt-model-name GPT_MODEL_NAME] [--whisper-model-type WHISPER_MODEL_TYPE] [--voice-rate VOICE_RATE]
talkgpt4all: error: unrecognized arguments: --gtp-model-name D:\Models\mistral-7b-openorca.Q4_0.gguf
(base) PS C:\Users\Administrator>

**Comment by vra** [comment]
Hi @Jacksninor , I guess that the version of GPT4all used in talkgpt4all is outdated. I will update talkgpt4all code base as soon as possible.
